<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма запись',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '%d0%bf%d0%be%d1%81%d0%bb%d0%b5-%d0%be%d1%82%d0%bf%d1%80%d0%b0%d0%b2%d0%ba%d0%b8.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'doktor-klimova@mail.ru',
		'to' => 'doktor-klimova@mail.ru'
	),
	'fields' => array(
		'custom_U601' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Имя\' не может быть пустым.'
			)
		),
		'custom_U595' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сообщение\' не может быть пустым.'
			)
		),
		'custom_U610' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Ваш телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваш телефон\' не может быть пустым.'
			)
		),
		'custom_U750' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Желаемая дата и время',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Желаемая дата и время\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
